### ISSUE TITLE
code not run due to sheet data not being private

### ISSUE THREAD

**Issue by jic007** [afsc-gap-products/gap_bs_data_report#14]
this bit is
# https://docs.google.com/spreadsheets/d/10Pn3fWkB-Jjcsz4iG7UlR-LXbIVYofy1yHhKkYZhv2M/edit?usp=sharing
  googledrive::drive_download(file = googledrive::as_id("10Pn3fWkB-Jjcsz4iG7UlR-LXbIVYofy1yHhKkYZhv2M"),
                              type = "csv",
                              overwrite = TRUE,
                              path = paste0(dir_out_rawdata, "/0_species_local_names"))

error below 
> source('./code/data.R')
[1] "Load data"
Error in `map()`:
ℹ In index: 1.
Caused by error in `.f()`:
! Client error: (404) Not Found
File not found: 10Pn3fWkB-Jjcsz4iG7UlR-LXbIVYofy1yHhKkYZhv2M.
• message: File not found: 10Pn3fWkB-Jjcsz4iG7UlR-LXbIVYofy1yHhKkYZhv2M.
• domain: global
• reason: notFound
• location: fileId
• locationType: parameter
Run `rlang::last_trace()` to see where the error occurred.
Warning messages:
1: attribute variables are assumed to be spatially constant throughout all geometries 
2: attribute variables are assumed to be spatially constant throughout all geometries 
3: attribute variables are assumed to be spatially constant throughout all geometries

**Comment by EmilyMarkowitz-NOAA** [comment]
I'm not sure exactly what this issue is asking to be addressed. Is the issue that there is no public access to this google spreadsheet file to reproduce the report? Unfortunately, the code in this repo is just posted in the spirit of transparency, and you won't be able to access this or any other data table used in this repo. 

Regarding the specific google spreadsheet linked: This is a fairly project- and team-specific table that would not make much sense outside of our group. Here is a screenshot of a few rows if you are curious: 
![image](https://github.com/afsc-gap-products/gap_bs_data_report/assets/75965120/9bb045ec-d1d6-452d-b868-c2098784f59b)

**Comment by jic007** [comment]
Thank you for this. Fair enough. Target was to reporduce the report only regardless of data.

 We'll see if the report could run without using the data.
